// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vjkovzjuhkgtqlhhhkgr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZqa292emp1aGtndHFsaGhoa2dyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMzIzNjUsImV4cCI6MjA3MzgwODM2NX0.17zrme8r0EkJSyRiw5RFyuISeecq2vGlO2JNGoG4nNg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});